apiVersion: v1
kind: Service
metadata:
  name: qserv
  labels: 
    app: qserv
spec:
  clusterIP: None
  ports:
  - port: 4040 
    targetPort: 4040
    protocol: TCP
    name: mysql-proxy
  selector:
    app: qserv
